website/music/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required, permission_required

app_name = 'music'


urlpatterns = [
    # /music/
    #url(r'^$', views.index, name='index'),
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/71/
   # url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album/add
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    #url(r'^me/$', views.test, name='test'),

    #/music/<album_id>/favorite/
    #url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    # /music/album/2/
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    #/music/album/2/delete
    url(r'^(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),

    url(r'^add_song/$', views.SongCreate.as_view(), name="add_song"),

    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    url(r'^login/$', views.UserLoginFormView.as_view(), name="login"),

    url(r'^logout/$', views.logout_view, name="logout"),
]

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .validators import validate_file_extension, valid
# Create your models here.


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField(validators=[valid])

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.fk})
        #return reverse('music:index')

website/music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class UserLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']



website/music/views.py
# from django.shortcuts import render

# Create your views here.

# from django.http import HttpResponse
#from django.http import HttpResponse
from django.http import Http404
#from django.template import loader
# from django.shortcuts import render, get_object_or_404
# from .models import Album, Song


# def index(request):
#     all_albums = Album.objects.all()
#     html = ''
#     for album in all_albums:
#         url = '/music/' + str(album.id) + '/'
#         html += '<a href="' + url + '">' + album.album_title + '</a><br>'
#     return HttpResponse(html)

# def index(request):
#     all_albums = Album.objects.all()
#     template = loader.get_template('music/index.html')
#     context = {'all_albums': all_albums}
#     return HttpResponse(template.render(context, request))

# def index(request):
#     all_albums = Album.objects.all()
#     context = {'all_albums': all_albums}
#     return render(request, 'music/index.html', context)


# def detail(request, album_id):
#     try:
#         album = Album.objects.get(pk=album_id)
#     except Album.DoesNotExist:
#         raise Http404("Album does not exist")
#     return render(request, 'music/detail.html', {'album': album})


# def detail(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     return render(request, 'music/detail.html', {'album': album})
#
#
# def test(request):
#     return HttpResponse("<h1>Hello World</h1>")
#
# def favorite(request, album_id):
#     album = get_object_or_404(Album, pk=album_id)
#     try:
#         selected_song = album.song_set.get(pk=request.POST['song'])
#     except (KeyError, Song.DoesNotExist):
#         return render(request, 'music/detial.html'), {
#             'album':album,
#              'error_message': "You did not select a valid Song",
#         }
#     else:
#         selected_song.is_favorite = True
#         selected_song.save()
#         return render(request, 'music/detail.html', {'album': album})

#fresh start
from django.views import generic
from .models import Album, Song
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm, UserLoginForm
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'all_albums'
    paginate_by = 10

    def get_queryset(self):
        if self.request.user.is_authenticated:
            return Album.objects.filter(user = self.request.user)
        else:
            return Album.objects.filter(user = None)


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'
    def get_object(self, *args, **kwargs):
        obj = super(DetailView, self).get_object(*args, **kwargs)
        if obj.user != self.request.user:
            raise PermissionDenied
        else:
            return obj



class AlbumCreate(LoginRequiredMixin, CreateView):
    login_url = "music:login"
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(AlbumCreate, self).form_valid(form)















class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    def get_object(self, *args, **kwargs):
        obj = super(AlbumUpdate, self).get_object(*args, **kwargs)
        if obj.user != self.request.user:
            raise PermissionDenied
        else:
            return obj

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class SongCreate(LoginRequiredMixin, CreateView):
    login_url = 'music:login'
    model = Song
    fields = ['album', 'file_type', 'song_title']


class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    #display blank form

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})


# def user_login(request):
#     username = request.POST['username']
#     password = request.POST['password']
#     user = authenticate(username=username, password=password)
#     if user is not None:
#         login(request, user)
#         redirect("music:index")
#     else:
#         redirect("music:login")

class UserLoginFormView(View):
    form_class = UserLoginForm
    template_name = "music/login_form.html"

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect("music:index")

        else:

            return redirect("music:login")
        #return render(request, self.template_name, {'form': form})

#def logout_view:
def logout_view(request):
    logout(request)
    return redirect('music:index')

website/music/templates/music/album_form.html
{% extends 'music/base.html' %}
{%block title %} Add a new Album {% endblock %}


{% block body %}
<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                <div class="panel-body">
                        <h3>Create a new Album</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10"  >
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
</div>
{%endblock%}

website/music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
{% load staticfiles %}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
<link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- header !-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'music:index' %}">
                    <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                    Albums</a></li>
                <li class=""><a href="#">
                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                    Songs</a></li>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class=""><a href={% url 'music:album-add' %}>
                    <span class="glyphicon glyphicon-plus aria-hidden="true"></span>&nbsp;
                    Add Album</a></li>

                <li class=""><a href={% url 'music:add_song' %}>
                    <span class="glyphicon glyphicon-plus aria-hidden="true"></span>&nbsp;
                    Add Song</a></li>

                <li class="">
                    {% if request.user.is_authenticated %}
                        <a href={% url 'music:logout' %}><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout</a></li>
                    {% else %}
                        <a href={% url 'music:login' %}><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Login</a></li>
                    {% endif %}

            </ul>
        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

website/music/templates/music/detail.html
{%extends 'music/base.html' %}
{% block title %}Album Details{% endblock %}
{%block body %}
    <img src="{{album.album_logo.url}}" style="height:300px;width:300px">

    <h1>{{ album.album_title}}</h1>
    <h3>{{ album.artist }}</h3>

    {% if error_message %}
        <p><strong>{{error_message}}</strong></p>
    {% endif %}


        {% for song in album.song_set.all %}
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
            <br>
        {% endfor %}
<a href = {% url 'music:album-update' album.id %}> <button type="button" class="btn btn-primary">Edit</button></a>
<form action ="{% url 'music:album-delete' album.id %}" method="post" style="display:inline" >
    {% csrf_token %}
    <input type="hidden" name="album_id" value="{{ album.id }}">
    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>

</form>
{% endblock %}

website/music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

website/music/templates/music/index.html
{%extends 'music/base.html' %}

{% block body %}

    {% if all_albums %}
        <h3>Here are all of your albums, {{ request.user.username }}</h3>
        <ul>
            {% for album in all_albums %}
            <li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
            <a href={% url 'music:album-update' album.id %} style="display:inline"> <span class="glyphicon glyphicon-pencil aria-hidden="true" ></span>&nbsp;</a>
            {% endfor %}
        </ul>
    {% else %}
        <h3>You don't have any albums</h3>
    {% endif %}
        {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="/music?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="/music?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

website/music/templates/music/login_form.html
{% extends 'music/base.html' %}
{%block title %} Register {% endblock %}


{% block body %}
<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Login</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group" style="display:inline" >
                            <a class="col-sm-offset-2 col-sm-10"  >
                                <button type="submit" class="btn btn-success">Login</button>
                                <a href= {% url 'music:register' %} /><button type="button" class="btn btn-success regbutton">Register</button></a>

                            </div>
                        </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
</div>
{%endblock%}

website/music/templates/music/registration_form.html
{% extends 'music/base.html' %}
{%block title %} Register {% endblock %}


{% block body %}
<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3>Create a new Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10"  >
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
</div>
{%endblock%}

website/music/templates/music/song_form.html
{% extends 'music/base.html' %}
{%block title %} Add a new Song{% endblock %}


{% block body %}
<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                <div class="panel-body">
                        <h3>Add a Song</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10"  >
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
</div>
{%endblock%}

website/music/templates/music/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello World</h1>
</body>
</html>